"use client";

import { useActionState, useState, useTransition } from "react";
import { useRouter } from "next/navigation";

import {
  createLottery,
  offerNextOnWaitlist,
  runLottery,
  type LotteryActionState,
} from "@/lib/lottery/actions";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { GRADES } from "@/lib/types";

export function NewLotteryForm({
  school,
  periods,
}: {
  school: string;
  periods: { id: string; name: string }[];
}) {
  const [state, formAction, pending] = useActionState<LotteryActionState, FormData>(
    createLottery,
    undefined
  );

  return (
    <form action={formAction} className="space-y-4">
      <input type="hidden" name="school" value={school} />
      <div className="grid gap-4 sm:grid-cols-2">
        <div className="space-y-2">
          <Label>Enrollment period</Label>
          <Select name="periodId" required>
            <SelectTrigger>
              <SelectValue placeholder="Choose period" />
            </SelectTrigger>
            <SelectContent>
              {periods.map((p) => (
                <SelectItem key={p.id} value={p.id}>
                  {p.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label>Grade</Label>
          <Select name="grade" required>
            <SelectTrigger>
              <SelectValue placeholder="Choose grade" />
            </SelectTrigger>
            <SelectContent>
              {GRADES.map((g) => (
                <SelectItem key={g} value={g}>
                  {g}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>
      <div className="grid gap-4 sm:grid-cols-3">
        <div className="space-y-2">
          <Label htmlFor="siblingWeight">Sibling weight</Label>
          <Input id="siblingWeight" name="siblingWeight" type="number" step="0.5" min={1} defaultValue={2} />
        </div>
        <div className="space-y-2">
          <Label htmlFor="staffChildWeight">Staff child weight</Label>
          <Input id="staffChildWeight" name="staffChildWeight" type="number" step="0.5" min={1} defaultValue={2} />
        </div>
        <div className="space-y-2">
          <Label htmlFor="zoneWeight">Zone weight</Label>
          <Input id="zoneWeight" name="zoneWeight" type="number" step="0.5" min={1} defaultValue={1} />
        </div>
      </div>
      <div className="space-y-2">
        <Label htmlFor="seed">Seed (optional — autogenerated if blank)</Label>
        <Input id="seed" name="seed" className="font-mono" placeholder="leave blank for a random seed" />
      </div>
      {state?.error && (
        <Alert variant="destructive">
          <AlertDescription>{state.error}</AlertDescription>
        </Alert>
      )}
      <Button type="submit" disabled={pending}>
        {pending ? "Creating…" : "Create lottery"}
      </Button>
    </form>
  );
}

export function RunLotteryButton({
  school,
  lotteryId,
  hasRun,
}: {
  school: string;
  lotteryId: string;
  hasRun: boolean;
}) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  return (
    <div className="flex items-center gap-2">
      {error && <span className="text-sm text-destructive">{error}</span>}
      <Button
        size="sm"
        variant={hasRun ? "outline" : "default"}
        disabled={pending}
        onClick={() => {
          setError(null);
          startTransition(async () => {
            const result = await runLottery({ school, lotteryId });
            if (result?.error) setError(result.error);
            else router.refresh();
          });
        }}
      >
        {pending ? "Running…" : hasRun ? "Rerun (same seed)" : "Run lottery"}
      </Button>
    </div>
  );
}

export function OfferNextButton({
  school,
  periodId,
  grade,
}: {
  school: string;
  periodId: string;
  grade: string;
}) {
  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  return (
    <div className="flex items-center gap-2">
      {error && <span className="text-sm text-destructive">{error}</span>}
      <Button
        size="sm"
        variant="outline"
        disabled={pending}
        onClick={() => {
          setError(null);
          startTransition(async () => {
            const result = await offerNextOnWaitlist({ school, periodId, grade });
            if (result?.error) setError(result.error);
            else router.refresh();
          });
        }}
      >
        {pending ? "Offering…" : "Offer next seat"}
      </Button>
    </div>
  );
}
